In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\chahat\Downloads\matches.csv",na_values=['nan',' ','na'])
df1 = pd.read_csv(r"C:\Users\chahat\Downloads\deliveries.csv",na_values=['nan',' ','na'])
df.head(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba
7,335989,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar
8,335990,2007/08,Hyderabad,2008-04-24,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson
9,335991,2007/08,Chandigarh,2008-04-25,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba

In [3]:
print(df.shape,df1.shape)

(1095, 20) (260920, 17)

In [4]:
print(df.columns,df1.columns)

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object') Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [5]:
df = df.rename(columns={'id':'match_id'})

In [6]:
df = pd.merge(df,df1,on='match_id')

In [7]:
df.shape

(260920, 36)

In [8]:
df.columns

Index(['match_id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [9]:
df.head(10)

,match_id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
5,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
6,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
7,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
8,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
9,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 36 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   season            260920 non-null  object
 2   city              248523 non-null  object
 3   date              260920 non-null  object
 4   match_type        260920 non-null  object
 5   player_of_match   260430 non-null  object
 6   venue             260920 non-null  object
 7   team1             260920 non-null  object
 8   team2             260920 non-null  object
 9   toss_winner       260920 non-null  object
 10  toss_decision     260920 non-null  object
 11  winner            260430 non-null  object
 12  result            260920 non-null  object
 13  result_margin     256796 non-null  float64
 14  target_runs       260611 non-null  float64
 15  target_overs      260611 non-null  float64
 16  super_over        260920 non-null  object
 17  method            3646 non-null    object
 18  umpire1           260920 non-null  object
 19  umpire2           260920 non-null  object
 20  inning            260920 non-null  int64
 21  batting_team      260920 non-null  object
 22  bowling_team      260920 non-null  object
 23  over              260920 non-null  int64
 24  ball              260920 non-null  int64
 25  batter            260920 non-null  object
 26  bowler            260920 non-null  object
 27  non_striker       260920 non-null  object
 28  batsman_runs      260920 non-null  int64
 29  extra_runs        260920 non-null  int64
 30  total_runs        260920 non-null  int64
 31  extras_type       14125 non-null   object
 32  is_wicket         260920 non-null  int64
 33  player_dismissed  12950 non-null   object
 34  dismissal_kind    12950 non-null   object
 35  fielder           9354 non-null    object
dtypes: float64(3), int64(8), object(25)
memory usage: 71.7+ MB

In [11]:
df.describe()

,match_id,result_margin,target_runs,target_overs,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket
count,2.609200e+05,256796.000000,260611.000000,260611.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000,260920.000000
mean,9.070665e+05,17.279451,167.290406,19.846742,1.483531,9.197677,3.624486,1.265001,0.067806,1.332807,0.049632
std,3.679913e+05,21.600307,32.165944,1.224266,0.502643,5.683484,1.814920,1.639298,0.343265,1.626416,0.217184
min,3.359820e+05,1.000000,43.000000,5.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483340e+05,6.000000,148.000000,20.000000,1.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,9.809670e+05,8.000000,167.000000,20.000000,1.000000,9.000000,4.000000,1.000000,0.000000,1.000000,0.000000
75%,1.254066e+06,20.000000,188.000000,20.000000,2.000000,14.000000,5.000000,1.000000,0.000000,1.000000,0.000000
max,1.426312e+06,146.000000,288.000000,20.000000,6.000000,19.000000,11.000000,6.000000,7.000000,7.000000,1.000000

In [12]:
a = df.select_dtypes(include=['object']).columns
b = df.select_dtypes(include=['int64']).columns
c = df.select_dtypes(include=['float64']).columns
print(a,"\n",b,"\n",c)

Index(['season', 'city', 'date', 'match_type', 'player_of_match', 'venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'super_over', 'method', 'umpire1', 'umpire2', 'batting_team',
       'bowling_team', 'batter', 'bowler', 'non_striker', 'extras_type',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')
 Index(['match_id', 'inning', 'over', 'ball', 'batsman_runs', 'extra_runs',
       'total_runs', 'is_wicket'],
      dtype='object')
 Index(['result_margin', 'target_runs', 'target_overs'], dtype='object')

In [13]:
for i in a:
    print(df[i].unique())

['2007/08' '2009' '2009/10' '2011' '2012' '2013' '2014' '2015' '2016'
 '2017' '2018' '2019' '2020/21' '2021' '2022' '2023' '2024']
['Bangalore' 'Chandigarh' 'Delhi' 'Mumbai' 'Kolkata' 'Jaipur' 'Hyderabad'
 'Chennai' 'Cape Town' 'Port Elizabeth' 'Durban' 'Centurion' 'East London'
 'Johannesburg' 'Kimberley' 'Bloemfontein' 'Ahmedabad' 'Cuttack' 'Nagpur'
 'Dharamsala' 'Kochi' 'Indore' 'Visakhapatnam' 'Pune' 'Raipur' 'Ranchi'
 'Abu Dhabi' nan 'Rajkot' 'Kanpur' 'Bengaluru' 'Dubai' 'Sharjah'
 'Navi Mumbai' 'Lucknow' 'Guwahati' 'Mohali']
['2008-04-18' '2008-04-19' '2008-04-20' '2008-04-21' '2008-04-22'
 '2008-04-23' '2008-04-24' '2008-04-25' '2008-04-26' '2008-04-27'
 '2008-04-28' '2008-04-29' '2008-04-30' '2008-05-01' '2008-05-02'
 '2008-05-03' '2008-05-04' '2008-05-05' '2008-05-06' '2008-05-07'
 '2008-05-08' '2008-05-09' '2008-05-10' '2008-05-11' '2008-05-12'
 '2008-05-13' '2008-05-14' '2008-05-15' '2008-05-16' '2008-05-17'
 '2008-05-18' '2008-05-19' '2008-05-20' '2008-05-21' '2008-05-23'
 '2008-05-24' '2008-05-25' '2008-05-26' '2008-05-27' '2008-05-28'
 '2008-05-30' '2008-05-31' '2008-06-01' '2009-04-18' '2009-04-19'
 '2009-04-20' '2009-04-21' '2009-04-22' '2009-04-23' '2009-04-24'
 '2009-04-25' '2009-04-26' '2009-04-27' '2009-04-28' '2009-04-29'
 '2009-04-30' '2009-05-01' '2009-05-02' '2009-05-03' '2009-05-04'
 '2009-05-05' '2009-05-06' '2009-05-07' '2009-05-08' '2009-05-09'
 '2009-05-10' '2009-05-11' '2009-05-12' '2009-05-13' '2009-05-14'
 '2009-05-15' '2009-05-16' '2009-05-17' '2009-05-18' '2009-05-19'
 '2009-05-20' '2009-05-21' '2009-05-22' '2009-05-23' '2009-05-24'
 '2010-03-12' '2010-03-13' '2010-03-14' '2010-03-15' '2010-03-16'
 '2010-03-17' '2010-03-18' '2010-03-19' '2010-03-20' '2010-03-21'
 '2010-03-22' '2010-03-23' '2010-03-24' '2010-03-25' '2010-03-26'
 '2010-03-27' '2010-03-28' '2010-03-29' '2010-03-30' '2010-03-31'
 '2010-04-01' '2010-04-02' '2010-04-03' '2010-04-04' '2010-04-05'
 '2010-04-06' '2010-04-07' '2010-04-08' '2010-04-09' '2010-04-10'
 '2010-04-11' '2010-04-12' '2010-04-13' '2010-04-14' '2010-04-15'
 '2010-04-16' '2010-04-17' '2010-04-18' '2010-04-19' '2010-04-21'
 '2010-04-22' '2010-04-24' '2010-04-25' '2011-04-08' '2011-04-09'
 '2011-04-10' '2011-04-11' '2011-04-12' '2011-04-13' '2011-04-14'
 '2011-04-15' '2011-04-16' '2011-04-17' '2011-04-18' '2011-04-19'
 '2011-04-20' '2011-04-21' '2011-04-22' '2011-04-23' '2011-04-24'
 '2011-04-25' '2011-04-26' '2011-04-27' '2011-04-28' '2011-04-29'
 '2011-04-30' '2011-05-01' '2011-05-02' '2011-05-03' '2011-05-04'
 '2011-05-05' '2011-05-06' '2011-05-07' '2011-05-08' '2011-05-09'
 '2011-05-10' '2011-05-11' '2011-05-12' '2011-05-13' '2011-05-14'
 '2011-05-15' '2011-05-16' '2011-05-17' '2011-05-18' '2011-05-19'
 '2011-05-20' '2011-05-21' '2011-05-22' '2011-05-24' '2011-05-25'
 '2011-05-27' '2011-05-28' '2012-04-04' '2012-04-05' '2012-04-06'
 '2012-04-07' '2012-04-08' '2012-04-09' '2012-04-10' '2012-04-11'
 '2012-04-12' '2012-04-13' '2012-04-14' '2012-04-15' '2012-04-16'
 '2012-04-17' '2012-04-18' '2012-04-19' '2012-04-20' '2012-04-21'
 '2012-04-22' '2012-04-23' '2012-04-24' '2012-04-25' '2012-04-26'
 '2012-04-27' '2012-04-28' '2012-04-29' '2012-04-30' '2012-05-01'
 '2012-05-02' '2012-05-03' '2012-05-04' '2012-05-05' '2012-05-06'
 '2012-05-07' '2012-05-08' '2012-05-09' '2012-05-10' '2012-05-11'
 '2012-05-12' '2012-05-13' '2012-05-14' '2012-05-15' '2012-05-16'
 '2012-05-17' '2012-05-18' '2012-05-19' '2012-05-20' '2012-05-22'
 '2012-05-23' '2012-05-25' '2012-05-27' '2013-04-03' '2013-04-04'
 '2013-04-05' '2013-04-06' '2013-04-07' '2013-04-08' '2013-04-09'
 '2013-04-10' '2013-04-11' '2013-04-12' '2013-04-13' '2013-04-14'
 '2013-04-15' '2013-04-16' '2013-04-17' '2013-04-18' '2013-04-19'
 '2013-04-20' '2013-04-21' '2013-04-22' '2013-04-23' '2013-04-24'
 '2013-04-25' '2013-04-26' '2013-04-27' '2013-04-28' '2013-04-29'
 '2013-04-30' '2013-05-01' '2013-05-02' '2013-05-03' '2013-05-04'
 '2013-05-05' '2013-05-06' '2013-05-07' '2013-05-08' '2013-05-09'
 '2013-05-10' '2013-05-11' '2013-05-12' '2013-05-13' '2013-05-14'
 '2013-05-15' '2013-05-16' '2013-05-17' '2013-05-18' '2013-05-19'
 '2013-05-21' '2013-05-22' '2013-05-24' '2013-05-26' '2014-04-16'
 '2014-04-17' '2014-04-18' '2014-04-19' '2014-04-20' '2014-04-21'
 '2014-04-22' '2014-04-23' '2014-04-24' '2014-04-25' '2014-04-26'
 '2014-04-27' '2014-04-28' '2014-04-29' '2014-04-30' '2014-05-02'
 '2014-05-03' '2014-05-04' '2014-05-05' '2014-05-06' '2014-05-07'
 '2014-05-08' '2014-05-09' '2014-05-10' '2014-05-11' '2014-05-12'
 '2014-05-13' '2014-05-14' '2014-05-15' '2014-05-18' '2014-05-19'
 '2014-05-20' '2014-05-21' '2014-05-22' '2014-05-23' '2014-05-24'
 '2014-05-25' '2014-05-27' '2014-05-28' '2014-05-30' '2014-06-01'
 '2015-04-08' '2015-04-09' '2015-04-10' '2015-04-11' '2015-04-12'
 '2015-04-13' '2015-04-14' '2015-04-15' '2015-04-16' '2015-04-17'
 '2015-04-18' '2015-04-19' '2015-04-20' '2015-04-21' '2015-04-22'
 '2015-04-23' '2015-04-24' '2015-04-25' '2015-04-26' '2015-04-27'
 '2015-04-28' '2015-04-29' '2015-04-30' '2015-05-01' '2015-05-02'
 '2015-05-03' '2015-05-04' '2015-05-05' '2015-05-06' '2015-05-07'
 '2015-05-08' '2015-05-09' '2015-05-10' '2015-05-11' '2015-05-12'
 '2015-05-13' '2015-05-14' '2015-05-15' '2015-05-16' '2015-05-17'
 '2015-05-19' '2015-05-20' '2015-05-22' '2015-05-24' '2016-04-09'
 '2016-04-10' '2016-04-11' '2016-04-12' '2016-04-13' '2016-04-14'
 '2016-04-15' '2016-04-16' '2016-04-17' '2016-04-18' '2016-04-19'
 '2016-04-20' '2016-04-21' '2016-04-22' '2016-04-23' '2016-04-24'
 '2016-04-25' '2016-04-26' '2016-04-27' '2016-04-28' '2016-04-29'
 '2016-04-30' '2016-05-01' '2016-05-02' '2016-05-03' '2016-05-04'
 '2016-05-05' '2016-05-06' '2016-05-07' '2016-05-08' '2016-05-09'
 '2016-05-10' '2016-05-11' '2016-05-12' '2016-05-13' '2016-05-14'
 '2016-05-15' '2016-05-16' '2016-05-17' '2016-05-18' '2016-05-19'
 '2016-05-20' '2016-05-21' '2016-05-22' '2016-05-24' '2016-05-25'
 '2016-05-27' '2016-05-29' '2017-04-05' '2017-04-06' '2017-04-07'
 '2017-04-08' '2017-04-09' '2017-04-10' '2017-04-11' '2017-04-12'
 '2017-04-13' '2017-04-14' '2017-04-15' '2017-04-16' '2017-04-17'
 '2017-04-18' '2017-04-19' '2017-04-20' '2017-04-21' '2017-04-22'
 '2017-04-23' '2017-04-24' '2017-04-26' '2017-04-27' '2017-04-28'
 '2017-04-29' '2017-04-30' '2017-05-01' '2017-05-02' '2017-05-03'
 '2017-05-04' '2017-05-05' '2017-05-06' '2017-05-07' '2017-05-08'
 '2017-05-09' '2017-05-10' '2017-05-11' '2017-05-12' '2017-05-13'
 '2017-05-14' '2017-05-16' '2017-05-17' '2017-05-19' '2017-05-21'
 '2018-04-07' '2018-04-08' '2018-04-09' '2018-04-10' '2018-04-11'
 '2018-04-12' '2018-04-13' '2018-04-14' '2018-04-15' '2018-04-16'
 '2018-04-17' '2018-04-18' '2018-04-19' '2018-04-20' '2018-04-21'
 '2018-04-22' '2018-04-23' '2018-04-24' '2018-04-25' '2018-04-26'
 '2018-04-27' '2018-04-28' '2018-04-29' '2018-04-30' '2018-05-01'
 '2018-05-02' '2018-05-03' '2018-05-04' '2018-05-05' '2018-05-06'
 '2018-05-07' '2018-05-08' '2018-05-09' '2018-05-10' '2018-05-11'
 '2018-05-12' '2018-05-13' '2018-05-14' '2018-05-15' '2018-05-16'
 '2018-05-17' '2018-05-18' '2018-05-19' '2018-05-20' '2018-05-22'
 '2018-05-23' '2018-05-25' '2018-05-27' '2019-03-23' '2019-03-24'
 '2019-03-25' '2019-03-26' '2019-03-27' '2019-03-28' '2019-03-29'
 '2019-03-30' '2019-03-31' '2019-04-01' '2019-04-02' '2019-04-03'
 '2019-04-04' '2019-04-05' '2019-04-06' '2019-04-07' '2019-04-08'
 '2019-04-09' '2019-04-10' '2019-04-11' '2019-04-12' '2019-04-13'
 '2019-04-14' '2019-04-15' '2019-04-16' '2019-04-17' '2019-04-18'
 '2019-04-19' '2019-04-20' '2019-04-21' '2019-04-22' '2019-04-23'
 '2019-04-24' '2019-04-25' '2019-04-26' '2019-04-27' '2019-04-28'
 '2019-04-29' '2019-04-30' '2019-05-01' '2019-05-02' '2019-05-03'
 '2019-05-04' '2019-05-05' '2019-05-07' '2019-05-08' '2019-05-10'
 '2019-05-12' '2020-09-19' '2020-09-20' '2020-09-21' '2020-09-22'
 '2020-09-23' '2020-09-24' '2020-09-25' '2020-09-26' '2020-09-27'
 '2020-09-28' '2020-09-29' '2020-09-30' '2020-10-01' '2020-10-02'
 '2020-10-03' '2020-10-04' '2020-10-05' '2020-10-06' '2020-10-07'
 '2020-10-08' '2020-10-09' '2020-10-10' '2020-10-11' '2020-10-12'
 '2020-10-13' '2020-10-14' '2020-10-15' '2020-10-16' '2020-10-17'
 '2020-10-18' '2020-10-19' '2020-10-20' '2020-10-21' '2020-10-22'
 '2020-10-23' '2020-10-24' '2020-10-25' '2020-10-26' '2020-10-27'
 '2020-10-28' '2020-10-29' '2020-10-30' '2020-10-31' '2020-11-01'
 '2020-11-02' '2020-11-03' '2020-11-05' '2020-11-06' '2020-11-08'
 '2020-11-10' '2021-04-09' '2021-04-10' '2021-04-11' '2021-04-12'
 '2021-04-13' '2021-04-14' '2021-04-15' '2021-04-16' '2021-04-17'
 '2021-04-18' '2021-04-19' '2021-04-20' '2021-04-21' '2021-04-22'
 '2021-04-23' '2021-04-24' '2021-04-25' '2021-04-26' '2021-04-27'
 '2021-04-28' '2021-04-29' '2021-04-30' '2021-05-01' '2021-05-02'
 '2021-09-19' '2021-09-20' '2021-09-21' '2021-09-22' '2021-09-23'
 '2021-09-24' '2021-09-25' '2021-09-26' '2021-09-27' '2021-09-28'
 '2021-09-29' '2021-09-30' '2021-10-01' '2021-10-02' '2021-10-03'
 '2021-10-04' '2021-10-05' '2021-10-06' '2021-10-07' '2021-10-08'
 '2021-10-10' '2021-10-11' '2021-10-13' '2021-10-15' '2022-03-26'
 '2022-03-27' '2022-03-28' '2022-03-29' '2022-03-30' '2022-03-31'
 '2022-04-01' '2022-04-02' '2022-04-03' '2022-04-04' '2022-04-05'
 '2022-04-06' '2022-04-07' '2022-04-08' '2022-04-09' '2022-04-10'
 '2022-04-11' '2022-04-12' '2022-04-13' '2022-04-14' '2022-04-15'
 '2022-04-16' '2022-04-17' '2022-04-18' '2022-04-19' '2022-04-20'
 '2022-04-21' '2022-04-22' '2022-04-23' '2022-04-24' '2022-04-25'
 '2022-04-26' '2022-04-27' '2022-04-28' '2022-04-29' '2022-04-30'
 '2022-05-01' '2022-05-02' '2022-05-03' '2022-05-04' '2022-05-05'
 '2022-05-06' '2022-05-07' '2022-05-08' '2022-05-09' '2022-05-10'
 '2022-05-11' '2022-05-12' '2022-05-13' '2022-05-14' '2022-05-15'
 '2022-05-16' '2022-05-17' '2022-05-18' '2022-05-19' '2022-05-20'
 '2022-05-21' '2022-05-22' '2022-05-24' '2022-05-25' '2022-05-27'
 '2022-05-29' '2023-03-31' '2023-04-01' '2023-04-02' '2023-04-03'
 '2023-04-04' '2023-04-05' '2023-04-06' '2023-04-07' '2023-04-08'
 '2023-04-09' '2023-04-10' '2023-04-11' '2023-04-12' '2023-04-13'
 '2023-04-14' '2023-04-15' '2023-04-16' '2023-04-17' '2023-04-18'
 '2023-04-19' '2023-04-20' '2023-04-21' '2023-04-22' '2023-04-23'
 '2023-04-24' '2023-04-25' '2023-04-26' '2023-04-27' '2023-04-28'
 '2023-04-29' '2023-04-30' '2023-05-01' '2023-05-02' '2023-05-03'
 '2023-05-04' '2023-05-05' '2023-05-06' '2023-05-07' '2023-05-08'
 '2023-05-09' '2023-05-10' '2023-05-11' '2023-05-12' '2023-05-13'
 '2023-05-14' '2023-05-15' '2023-05-16' '2023-05-17' '2023-05-18'
 '2023-05-19' '2023-05-20' '2023-05-21' '2023-05-23' '2023-05-24'
 '2023-05-26' '2023-05-29' '2024-03-22' '2024-03-23' '2024-03-24'
 '2024-03-25' '2024-03-26' '2024-03-27' '2024-03-28' '2024-03-29'
 '2024-03-30' '2024-03-31' '2024-04-01' '2024-04-02' '2024-04-03'
 '2024-04-04' '2024-04-05' '2024-04-06' '2024-04-07' '2024-04-08'
 '2024-04-09' '2024-04-10' '2024-04-11' '2024-04-12' '2024-04-13'
 '2024-04-14' '2024-04-15' '2024-04-16' '2024-04-17' '2024-04-18'
 '2024-04-19' '2024-04-20' '2024-04-21' '2024-04-22' '2024-04-23'
 '2024-04-24' '2024-04-25' '2024-04-26' '2024-04-27' '2024-04-28'
 '2024-04-29' '2024-04-30' '2024-05-01' '2024-05-02' '2024-05-03'
 '2024-05-04' '2024-05-05' '2024-05-06' '2024-05-07' '2024-05-08'
 '2024-05-09' '2024-05-10' '2024-05-11' '2024-05-12' '2024-05-14'
 '2024-05-15' '2024-05-17' '2024-05-18' '2024-05-19' '2024-05-21'
 '2024-05-22' '2024-05-24' '2024-05-26']
['League' 'Semi Final' 'Final' '3rd Place Play-Off' 'Qualifier 1'
 'Elimination Final' 'Qualifier 2' 'Eliminator']
['BB McCullum' 'MEK Hussey' 'MF Maharoof' 'MV Boucher' 'DJ Hussey'
 'SR Watson' 'V Sehwag' 'ML Hayden' 'YK Pathan' 'KC Sangakkara' 'JDP Oram'
 'AC Gilchrist' 'SM Katich' 'MS Dhoni' 'ST Jayasuriya' 'GD McGrath'
 'SE Marsh' 'SA Asnodkar' 'IK Pathan' 'P Kumar' 'SM Pollock'
 'Sohail Tanvir' 'S Sreesanth' 'A Nehra' 'SC Ganguly' 'L Balaji'
 'Shoaib Akhtar' 'A Mishra' 'DPMD Jayawardene' 'GC Smith' 'DJ Bravo'
 'M Ntini' 'SP Goswami' 'A Kumble' 'KD Karthik' 'JA Morkel'
 'R Vinay Kumar' 'Umar Gul' 'SK Raina' 'CRD Fernando' 'SR Tendulkar'
 'R Dravid' 'DL Vettori' 'RP Singh' 'M Muralitharan' 'CH Gayle'
 'AB de Villiers' 'RS Bopara' 'PP Ojha' 'TM Dilshan' 'HH Gibbs'
 'DP Nannes' 'JP Duminy' 'Yuvraj Singh' 'SB Jakati' 'JH Kallis'
 'G Gambhir' 'RG Sharma' 'A Singh' 'S Badrinath' 'DR Smith' 'LRPL Taylor'
 'Harbhajan Singh' 'R Bhatia' 'SK Warne' 'B Lee' 'BJ Hodge' 'LR Shukla'
 'MK Pandey' 'AD Mathews' 'MK Tiwary' 'WPUJC Vaas' 'A Symonds'
 'AA Jhunjhunwala' 'J Theron' 'RV Uthappa' 'AC Voges' 'KM Jadhav'
 'NV Ojha' 'DA Warner' 'SL Malinga' 'M Vijay' 'KP Pietersen' 'AT Rayudu'
 'PD Collingwood' 'MJ Lumb' 'TL Suman' 'RJ Harris' 'PP Chawla'
 'Harmeet Singh' 'KA Pollard' 'R Ashwin' 'R McLaren' 'JD Unadkat'
 'M Kartik' 'DE Bollinger' 'S Anirudha' 'SK Trivedi' 'SB Wagh'
 'PC Valthaty' 'MD Mishra' 'DW Steyn' 'S Sohal' 'MM Patel' 'V Kohli'
 'I Sharma' 'J Botha' 'Iqbal Abdulla' 'P Parameswaran' 'R Sharma'
 'MR Marsh' 'BA Bhatt' 'S Aravind' 'WP Saha' 'S Dhawan' nan 'JEC Franklin'
 'RE Levi' 'SPD Smith' 'AM Rahane' 'RA Jadeja' 'MN Samuels' 'M Morkel'
 'F du Plessis' 'AD Mascarenhas' 'Shakib Al Hasan' 'JD Ryder' 'SP Narine'
 'S Nadeem' 'KMDN Kulasekara' 'CL White' 'Mandeep Singh' 'P Negi'
 'Azhar Mahmood' 'BW Hilfenhaus' 'A Chandila' 'UT Yadav' 'MS Bisla'
 'M Vohra' 'GH Vihari' 'AJ Finch' 'JP Faulkner' 'MS Gony' 'DA Miller'
 'SV Samson' 'DJG Sammy' 'MG Johnson' 'KK Cooper' 'PA Patel' 'AP Tare'
 'LJ Wright' 'YS Chahal' 'GJ Maxwell' 'CA Lynn' 'MM Sharma' 'PV Tambe'
 'Sandeep Sharma' 'B Kumar' 'CJ Anderson' 'KK Nair' 'AR Patel'
 'LMP Simmons' 'DJ Hooda' 'GJ Bailey' 'MA Agarwal' 'AD Russell' 'SS Iyer'
 'MA Starc' 'VR Aaron' 'TA Boult' 'NM Coulter-Nile' 'EJG Morgan'
 'HH Pandya' 'MC Henriques' 'Z Khan' 'MJ McClenaghan' 'Q de Kock'
 'Mustafizur Rahman' 'SA Yadav' 'AB Dinda' 'CH Morris' 'CR Brathwaite'
 'RR Pant' 'MP Stoinis' 'A Zampa' 'KH Pandya' 'HM Amla' 'BCJ Cutting'
 'Rashid Khan' 'N Rana' 'JJ Bumrah' 'AJ Tye' 'BA Stokes' 'KS Williamson'
 'JC Buttler' 'LH Ferguson' 'Mohammed Shami' 'RA Tripathi'
 'Mohammed Siraj' 'HV Patel' 'Washington Sundar' 'KV Sharma' 'KL Rahul'
 'SW Billings' 'JJ Roy' 'B Stanlake' 'JC Archer' 'AS Rajpoot' 'TG Southee'
 'Mujeeb Ur Rahman' 'Ishan Kishan' 'Kuldeep Yadav' 'S Gopal' 'L Ngidi'
 'PP Shaw' 'JM Bairstow' 'SM Curran' 'AS Joseph' 'K Rabada' 'HF Gurney'
 'DL Chahar' 'Imran Tahir' 'KMA Paul' 'KK Ahmed' 'Shubman Gill'
 'SO Hetmyer' 'Shivam Mavi' 'PK Garg' 'R Tewatia' 'A Nortje' 'CV Varun'
 'CJ Jordan' 'RD Gaikwad' 'PJ Cummins' 'RD Chahar' 'MM Ali' 'D Padikkal'
 'Harpreet Brar' 'Kartik Tyagi' 'JO Holder' 'JR Hazlewood' 'KS Bharat'
 'VR Iyer' 'OF Smith' 'PWH de Silva' 'E Lewis' 'LS Livingstone'
 'Avesh Khan' 'Abhishek Sharma' 'Anuj Rawat' 'S Dube' 'Umran Malik'
 'Mukesh Choudhary' 'M Jansen' 'R Parag' 'Mohsin Khan' 'RK Singh'
 'TH David' 'YBK Jaiswal' 'DP Conway' 'DR Sams' 'SN Thakur' 'RM Patidar'
 'Arshdeep Singh' 'MA Wood' 'B Sai Sudharsan' 'NT Ellis' 'N Pooran'
 'HC Brook' 'Sikandar Raza' 'C Green' 'A Manohar' 'J Little' 'M Pathirana'
 'PD Salt' 'GD Phillips' 'PN Mankad' 'P Simran Singh' 'WD Parnell'
 'RR Rossouw' 'Akash Madhwal' 'MP Yadav' 'Shashank Singh' 'R Shepherd'
 'Yash Thakur' 'Nithish Kumar Reddy' 'TM Head' 'R Sai Kishore'
 'J Fraser-McGurk' 'WG Jacks' 'Simarjeet Singh' 'Shahbaz Ahmed']
['M Chinnaswamy Stadium' 'Punjab Cricket Association Stadium, Mohali'
 'Feroz Shah Kotla' 'Wankhede Stadium' 'Eden Gardens'
 'Sawai Mansingh Stadium' 'Rajiv Gandhi International Stadium, Uppal'
 'MA Chidambaram Stadium, Chepauk' 'Dr DY Patil Sports Academy' 'Newlands'
 "St George's Park" 'Kingsmead' 'SuperSport Park' 'Buffalo Park'
 'New Wanderers Stadium' 'De Beers Diamond Oval' 'OUTsurance Oval'
 'Brabourne Stadium' 'Sardar Patel Stadium, Motera' 'Barabati Stadium'
 'Brabourne Stadium, Mumbai'
 'Vidarbha Cricket Association Stadium, Jamtha'
 'Himachal Pradesh Cricket Association Stadium' 'Nehru Stadium'
 'Holkar Cricket Stadium'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'
 'Subrata Roy Sahara Stadium' 'Maharashtra Cricket Association Stadium'
 'Shaheed Veer Narayan Singh International Stadium'
 'JSCA International Stadium Complex' 'Sheikh Zayed Stadium'
 'Sharjah Cricket Stadium' 'Dubai International Cricket Stadium'
 'Punjab Cricket Association IS Bindra Stadium, Mohali'
 'Saurashtra Cricket Association Stadium' 'Green Park'
 'M.Chinnaswamy Stadium' 'Punjab Cricket Association IS Bindra Stadium'
 'Rajiv Gandhi International Stadium' 'MA Chidambaram Stadium'
 'Arun Jaitley Stadium' 'MA Chidambaram Stadium, Chepauk, Chennai'
 'Wankhede Stadium, Mumbai' 'Narendra Modi Stadium, Ahmedabad'
 'Arun Jaitley Stadium, Delhi' 'Zayed Cricket Stadium, Abu Dhabi'
 'Dr DY Patil Sports Academy, Mumbai'
 'Maharashtra Cricket Association Stadium, Pune' 'Eden Gardens, Kolkata'
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh'
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow'
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad'
 'M Chinnaswamy Stadium, Bengaluru' 'Barsapara Cricket Stadium, Guwahati'
 'Sawai Mansingh Stadium, Jaipur'
 'Himachal Pradesh Cricket Association Stadium, Dharamsala'
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam']
['Royal Challengers Bangalore' 'Kings XI Punjab' 'Delhi Daredevils'
 'Mumbai Indians' 'Kolkata Knight Riders' 'Rajasthan Royals'
 'Deccan Chargers' 'Chennai Super Kings' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Lucknow Super Giants' 'Gujarat Titans'
 'Royal Challengers Bengaluru']
['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Royal Challengers Bangalore' 'Deccan Chargers' 'Kings XI Punjab'
 'Delhi Daredevils' 'Mumbai Indians' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Rising Pune Supergiants'
 'Gujarat Lions' 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings'
 'Gujarat Titans' 'Lucknow Super Giants' 'Royal Challengers Bengaluru']
['Royal Challengers Bangalore' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kings XI Punjab'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals'
 'Punjab Kings' 'Gujarat Titans' 'Lucknow Super Giants'
 'Royal Challengers Bengaluru']
['field' 'bat']
['Kolkata Knight Riders' 'Chennai Super Kings' 'Delhi Daredevils'
 'Royal Challengers Bangalore' 'Rajasthan Royals' 'Kings XI Punjab'
 'Deccan Chargers' 'Mumbai Indians' 'Pune Warriors' 'Kochi Tuskers Kerala'
 nan 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Rising Pune Supergiant' 'Delhi Capitals' 'Punjab Kings' 'Gujarat Titans'
 'Lucknow Super Giants' 'Royal Challengers Bengaluru']
['runs' 'wickets' 'tie' 'no result']
['N' 'Y']
[nan 'D/L']
['Asad Rauf' 'MR Benson' 'Aleem Dar' 'SJ Davis' 'BF Bowden' 'IL Howell'
 'DJ Harper' 'RE Koertzen' 'BR Doctrove' 'AV Jayaprakash' 'BG Jerling'
 'M Erasmus' 'HDPK Dharmasena' 'S Asnani' 'GAV Baxter' 'SS Hazare'
 'K Hariharan' 'SL Shastri' 'SK Tarapore' 'S Ravi' 'SJA Taufel' 'S Das'
 'AM Saheba' 'PR Reiffel' 'JD Cloete' 'AK Chaudhary' 'VA Kulkarni'
 'BNJ Oxenford' 'CK Nandan' 'C Shamshuddin' 'NJ Llong' 'RK Illingworth'
 'RM Deshpande' 'K Srinath' 'SD Fry' 'CB Gaffaney' 'PG Pathak'
 'Nitin Menon' 'K Bharatan' 'AY Dandekar' 'KN Ananthapadmanabhan'
 'A Nand Kishore' 'A Deshmukh' 'YC Barde' 'IJ Gould' 'RJ Tucker'
 'VK Sharma' 'UV Gandhe' 'K Srinivasan' 'J Madanagopal' 'Navdeep Singh'
 'MA Gough' 'Tapan Sharma' 'Chirra Ravikanthreddy' 'GR Sadashiv Iyer'
 'NA Patwardhan' 'HAS Khalid' 'R Pandit' 'A Totre' 'Vinod Seshan'
 'AG Wharf' 'MV Saidharshan Kumar']
['RE Koertzen' 'SL Shastri' 'GA Pratapkumar' 'DJ Harper' 'K Hariharan'
 'RB Tiffin' 'AM Saheba' 'MR Benson' 'IL Howell' 'AV Jayaprakash'

In [14]:
df['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [15]:
df['team1'] = df['team1'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Kings XI Punjab':'Punjab Kings',
                           'Delhi Daredevils':'Delhi Capitals','Rising Pune Supergiants':'Rising Pune Supergiant'})

In [16]:
df['team1'].unique()

array(['Royal Challengers Bengaluru', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Deccan Chargers', 'Chennai Super Kings', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Sunrisers Hyderabad', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Lucknow Super Giants', 'Gujarat Titans'],
      dtype=object)

In [17]:
df['team2'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Royal Challengers Bangalore', 'Deccan Chargers',
       'Kings XI Punjab', 'Delhi Daredevils', 'Mumbai Indians',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [18]:
df['team2'] = df['team2'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Kings XI Punjab':'Punjab Kings',
                           'Delhi Daredevils':'Delhi Capitals','Rising Pune Supergiants':'Rising Pune Supergiant'})

In [19]:
df['team2'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Royal Challengers Bengaluru', 'Deccan Chargers', 'Punjab Kings',
       'Delhi Capitals', 'Mumbai Indians', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Sunrisers Hyderabad', 'Rising Pune Supergiant',
       'Gujarat Lions', 'Gujarat Titans', 'Lucknow Super Giants'],
      dtype=object)

In [20]:
df['toss_winner'] = df['toss_winner'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Kings XI Punjab':'Punjab Kings',
                           'Delhi Daredevils':'Delhi Capitals','Rising Pune Supergiants':'Rising Pune Supergiant'})

In [21]:
df['toss_winner'].unique()

array(['Royal Challengers Bengaluru', 'Chennai Super Kings',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Punjab Kings', 'Kolkata Knight Riders', 'Delhi Capitals',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiant', 'Gujarat Titans',
       'Lucknow Super Giants'], dtype=object)

In [22]:
df['winner'] = df['winner'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Kings XI Punjab':'Punjab Kings',
                           'Delhi Daredevils':'Delhi Capitals','Rising Pune Supergiants':'Rising Pune Supergiant'})

In [23]:
df['winner'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Capitals',
       'Royal Challengers Bengaluru', 'Rajasthan Royals', 'Punjab Kings',
       'Deccan Chargers', 'Mumbai Indians', 'Pune Warriors',
       'Kochi Tuskers Kerala', nan, 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Gujarat Titans',
       'Lucknow Super Giants'], dtype=object)

In [24]:
df['batting_team'] = df['batting_team'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Kings XI Punjab':'Punjab Kings',
                           'Delhi Daredevils':'Delhi Capitals','Rising Pune Supergiants':'Rising Pune Supergiant'})

In [25]:
df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bengaluru',
       'Chennai Super Kings', 'Punjab Kings', 'Rajasthan Royals',
       'Delhi Capitals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Lucknow Super Giants',
       'Gujarat Titans'], dtype=object)

In [26]:
df['bowling_team'] = df['bowling_team'].replace({'Royal Challengers Bangalore':'Royal Challengers Bengaluru','Kings XI Punjab':'Punjab Kings',
                           'Delhi Daredevils':'Delhi Capitals','Rising Pune Supergiants':'Rising Pune Supergiant'})

In [27]:
df['bowling_team'].unique()

array(['Royal Challengers Bengaluru', 'Kolkata Knight Riders',
       'Punjab Kings', 'Chennai Super Kings', 'Delhi Capitals',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Gujarat Titans',
       'Lucknow Super Giants'], dtype=object)

In [28]:
df['season'] = df['season'].replace({'2007/08':'2008','2009/10':'2010','2020/21':'2020'})

In [29]:
df['season'].unique()

array(['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023',
       '2024'], dtype=object)

In [30]:
df['city'] = df['city'].replace({'Bangalore':'Bengaluru'})

In [31]:
df['city'].unique()

array(['Bengaluru', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Dubai', 'Sharjah',
       'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'], dtype=object)

In [32]:
df['match_type'].unique()

array(['League', 'Semi Final', 'Final', '3rd Place Play-Off',
       'Qualifier 1', 'Elimination Final', 'Qualifier 2', 'Eliminator'],
      dtype=object)

In [33]:
df.isnull().sum()

match_id                 0
season                   0
city                 12397
date                     0
match_type               0
player_of_match        490
venue                    0
team1                    0
team2                    0
toss_winner              0
toss_decision            0
winner                 490
result                   0
result_margin         4124
target_runs            309
target_overs           309
super_over               0
method              257274
umpire1                  0
umpire2                  0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [34]:
df['city'].unique()

array(['Bengaluru', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Dubai', 'Sharjah',
       'Navi Mumbai', 'Lucknow', 'Guwahati', 'Mohali'], dtype=object)

In [35]:
df['team1'].unique()

array(['Royal Challengers Bengaluru', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Deccan Chargers', 'Chennai Super Kings', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Sunrisers Hyderabad', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Lucknow Super Giants', 'Gujarat Titans'],
      dtype=object)

In [36]:
df.groupby('venue')['city'].unique()

venue
Arun Jaitley Stadium                                                                   [Delhi]
Arun Jaitley Stadium, Delhi                                                            [Delhi]
Barabati Stadium                                                                     [Cuttack]
Barsapara Cricket Stadium, Guwahati                                                 [Guwahati]
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow                [Lucknow]
Brabourne Stadium                                                                     [Mumbai]
Brabourne Stadium, Mumbai                                                             [Mumbai]
Buffalo Park                                                                     [East London]
De Beers Diamond Oval                                                              [Kimberley]
Dr DY Patil Sports Academy                                                            [Mumbai]
Dr DY Patil Sports Academy, Mumbai                                       [Mumbai, Navi Mumbai]
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium                            [Visakhapatnam]
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam             [Visakhapatnam]
Dubai International Cricket Stadium                                               [nan, Dubai]
Eden Gardens                                                                         [Kolkata]
Eden Gardens, Kolkata                                                                [Kolkata]
Feroz Shah Kotla                                                                       [Delhi]
Green Park                                                                            [Kanpur]
Himachal Pradesh Cricket Association Stadium                                      [Dharamsala]
Himachal Pradesh Cricket Association Stadium, Dharamsala                          [Dharamsala]
Holkar Cricket Stadium                                                                [Indore]
JSCA International Stadium Complex                                                    [Ranchi]
Kingsmead                                                                             [Durban]
M Chinnaswamy Stadium                                                              [Bengaluru]
M Chinnaswamy Stadium, Bengaluru                                                   [Bengaluru]
M.Chinnaswamy Stadium                                                              [Bengaluru]
MA Chidambaram Stadium                                                               [Chennai]
MA Chidambaram Stadium, Chepauk                                                      [Chennai]
MA Chidambaram Stadium, Chepauk, Chennai                                             [Chennai]
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur                    [Mohali]
Maharashtra Cricket Association Stadium                                                 [Pune]
Maharashtra Cricket Association Stadium, Pune                                           [Pune]
Narendra Modi Stadium, Ahmedabad                                                   [Ahmedabad]
Nehru Stadium                                                                          [Kochi]
New Wanderers Stadium                                                           [Johannesburg]
Newlands                                                                           [Cape Town]
OUTsurance Oval                                                                 [Bloemfontein]
Punjab Cricket Association IS Bindra Stadium                                      [Chandigarh]
Punjab Cricket Association IS Bindra Stadium, Mohali                              [Chandigarh]
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh                  [Chandigarh]
Punjab Cricket Association Stadium, Mohali                                        [Chandigarh]
Rajiv Gandhi International Stadium                                                 [Hyderabad]
Rajiv Gandhi International Stadium, Uppal                                          [Hyderabad]
Rajiv Gandhi International Stadium, Uppal, Hyderabad                               [Hyderabad]
Sardar Patel Stadium, Motera                                                       [Ahmedabad]
Saurashtra Cricket Association Stadium                                                [Rajkot]
Sawai Mansingh Stadium                                                                [Jaipur]
Sawai Mansingh Stadium, Jaipur                                                        [Jaipur]
Shaheed Veer Narayan Singh International Stadium                                      [Raipur]
Sharjah Cricket Stadium                                                         [nan, Sharjah]
Sheikh Zayed Stadium                                                               [Abu Dhabi]
St George's Park                                                              [Port Elizabeth]
Subrata Roy Sahara Stadium                                                              [Pune]
SuperSport Park                                                                    [Centurion]
Vidarbha Cricket Association Stadium, Jamtha                                          [Nagpur]
Wankhede Stadium                                                                      [Mumbai]
Wankhede Stadium, Mumbai                                                              [Mumbai]
Zayed Cricket Stadium, Abu Dhabi                                                   [Abu Dhabi]
Name: city, dtype: object

In [37]:
df[df['city'].isna()]['venue'].unique()

array(['Sharjah Cricket Stadium', 'Dubai International Cricket Stadium'],
      dtype=object)

In [38]:
new_city = {
    'Sharjah Cricket Stadium':'Sharjah',
    'Dubai International Cricket Stadium':'Dubai'
}
df['city'] = df['city'].fillna(df['venue'].map(new_city))

In [39]:
df['city'].isnull().sum()

np.int64(0)

In [40]:
df['city'].unique()

array(['Bengaluru', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Sharjah', 'Dubai', 'Rajkot', 'Kanpur', 'Navi Mumbai',
       'Lucknow', 'Guwahati', 'Mohali'], dtype=object)

In [41]:
df[df['player_of_match'].isna()]['date'].unique()

array(['2011-05-21', '2015-04-29', '2015-05-17', '2019-04-30',
       '2023-05-03'], dtype=object)

In [42]:
df[df['player_of_match'].isna()]['team1'].unique()

array(['Delhi Capitals', 'Royal Challengers Bengaluru',
       'Lucknow Super Giants'], dtype=object)

In [43]:
df[df['player_of_match'].isna()]['team2'].unique()

array(['Pune Warriors', 'Rajasthan Royals', 'Delhi Capitals',
       'Chennai Super Kings'], dtype=object)

In [44]:
df[df['player_of_match'].isna()]['match_type'].unique()

array(['League'], dtype=object)

In [45]:
df['player_of_match'] = df['player_of_match'].fillna("match_cancelled")

In [46]:
df[df['winner'].isna()]['date'].unique()

array(['2011-05-21', '2015-04-29', '2015-05-17', '2019-04-30',
       '2023-05-03'], dtype=object)

In [47]:
df['winner'] = df['winner'].fillna("match_cancelled")

In [48]:
df[df['result_margin'].isna()]['date'].unique()

array(['2009-04-23', '2010-03-21', '2011-05-21', '2013-04-07',
       '2013-04-16', '2014-04-29', '2015-04-21', '2015-04-29',
       '2015-05-17', '2017-04-29', '2019-03-30', '2019-04-30',
       '2019-05-02', '2020-09-20', '2020-09-28', '2020-10-18',
       '2021-04-25', '2023-05-03'], dtype=object)

In [49]:
new_margin = {
    '2009-04-23':999,
    '2010-03-21':999,
    '2011-05-21':999,
    '2013-04-07':999,
    '2013-04-16':999,
    '2014-04-29':999,
    '2015-04-21':999,
    '2015-04-29':999,
    '2015-05-17':999,
    '2017-04-29':999,
    '2019-03-30':999,
    '2019-04-30':999,
    '2019-05-02':999,
    '2020-09-20':999,
    '2020-09-28':999,
    '2020-10-18':999,
    '2021-04-25':999,
    '2023-05-03':999
}
df['result_margin'] = df['result_margin'].fillna(df['date'].map(new_margin))

In [50]:
df[(df['result_margin'].isna()) & (df['date']=='2019-05-02')][['team1','team2']]

Empty DataFrame
Columns: [team1, team2]
Index: []

In [51]:
df[df['target_runs'].isna()]['date'].unique()

array(['2011-05-21', '2015-04-29', '2023-05-03'], dtype=object)

In [52]:
df[(df['date']=='2015-05-17')]['target_runs'].unique()

array([188., 114.])

In [53]:
df['target_runs'].describe()

count    260611.000000
mean        167.290406
std          32.165944
min          43.000000
25%         148.000000
50%         167.000000
75%         188.000000
max         288.000000
Name: target_runs, dtype: float64

In [54]:
df[df['target_runs'].isna()]['winner'].unique()

array(['match_cancelled'], dtype=object)

In [55]:
df['target_runs'] = df['target_runs'].fillna(999)

In [56]:
df[df['target_overs'].isna()]['winner'].unique()

array(['match_cancelled'], dtype=object)

In [57]:
df['target_overs'] = df['target_overs'].fillna(999)

In [58]:
df['method'].unique()

array([nan, 'D/L'], dtype=object)

In [59]:
df[df['method']=='D/L']['date'].unique()

array(['2008-05-17', '2008-05-18', '2009-04-19', '2009-04-21',
       '2009-05-07', '2011-04-18', '2011-05-07', '2011-05-14',
       '2014-05-10', '2015-04-22', '2015-05-15', '2016-04-26',
       '2016-05-14', '2016-05-17', '2016-05-18', '2017-05-17',
       '2018-04-11', '2018-04-21', '2018-05-02', '2023-04-01',
       '2023-05-29'], dtype=object)

In [60]:
df['method'] = df['method'].fillna('No_D/L')

In [61]:
df['extras_type'].unique()

array(['legbyes', nan, 'wides', 'byes', 'noballs', 'penalty'],
      dtype=object)

In [62]:
df['extras_type'] = df['extras_type'].fillna('normal')

In [63]:
df['dismissal_kind'].unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field', 'retired out'], dtype=object)

In [64]:
df['player_dismissed'] = df['player_dismissed'].fillna('No_wicket')

In [65]:
df['dismissal_kind'] = df['dismissal_kind'].fillna('No_wicket')

In [66]:
df['fielder'] = df['fielder'].fillna('No_wicket')

In [67]:
df.isnull().sum()

match_id            0
season              0
city                0
date                0
match_type          0
player_of_match     0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
winner              0
result              0
result_margin       0
target_runs         0
target_overs        0
super_over          0
method              0
umpire1             0
umpire2             0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
dtype: int64

In [68]:
df.to_csv('ipl.csv',index=False)

In [69]:
df['winner'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Capitals',
       'Royal Challengers Bengaluru', 'Rajasthan Royals', 'Punjab Kings',
       'Deccan Chargers', 'Mumbai Indians', 'Pune Warriors',
       'Kochi Tuskers Kerala', 'match_cancelled', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Gujarat Titans',
       'Lucknow Super Giants'], dtype=object)

In [70]:
df[['team1','team2']]

                              team1                  team2
0       Royal Challengers Bengaluru  Kolkata Knight Riders
1       Royal Challengers Bengaluru  Kolkata Knight Riders
2       Royal Challengers Bengaluru  Kolkata Knight Riders
3       Royal Challengers Bengaluru  Kolkata Knight Riders
4       Royal Challengers Bengaluru  Kolkata Knight Riders
...                             ...                    ...
260915          Sunrisers Hyderabad  Kolkata Knight Riders
260916          Sunrisers Hyderabad  Kolkata Knight Riders
260917          Sunrisers Hyderabad  Kolkata Knight Riders
260918          Sunrisers Hyderabad  Kolkata Knight Riders
260919          Sunrisers Hyderabad  Kolkata Knight Riders

[260920 rows x 2 columns]

In [71]:
df.reset_index(inplace=True)

In [72]:
df.loc[1]

index                                         1
match_id                                 335982
season                                     2008
city                                  Bengaluru
date                                 2008-04-18
match_type                               League
player_of_match                     BB McCullum
venue                     M Chinnaswamy Stadium
team1               Royal Challengers Bengaluru
team2                     Kolkata Knight Riders
toss_winner         Royal Challengers Bengaluru
toss_decision                             field
winner                    Kolkata Knight Riders
result                                     runs
result_margin                             140.0
target_runs                               223.0
target_overs                               20.0
super_over                                    N
method                                   No_D/L
umpire1                               Asad Rauf
umpire2                             RE Koertzen
inning                                        1
batting_team              Kolkata Knight Riders
bowling_team        Royal Challengers Bengaluru
over                                          0
ball                                          2
batter                              BB McCullum
bowler                                  P Kumar
non_striker                          SC Ganguly
batsman_runs                                  0
extra_runs                                    0
total_runs                                    0
extras_type                              normal
is_wicket                                     0
player_dismissed                      No_wicket
dismissal_kind                        No_wicket
fielder                               No_wicket
Name: 1, dtype: object

In [73]:
df.iloc[1]

index                                         1
match_id                                 335982
season                                     2008
city                                  Bengaluru
date                                 2008-04-18
match_type                               League
player_of_match                     BB McCullum
venue                     M Chinnaswamy Stadium
team1               Royal Challengers Bengaluru
team2                     Kolkata Knight Riders
toss_winner         Royal Challengers Bengaluru
toss_decision                             field
winner                    Kolkata Knight Riders
result                                     runs
result_margin                             140.0
target_runs                               223.0
target_overs                               20.0
super_over                                    N
method                                   No_D/L
umpire1                               Asad Rauf
umpire2                             RE Koertzen
inning                                        1
batting_team              Kolkata Knight Riders
bowling_team        Royal Challengers Bengaluru
over                                          0
ball                                          2
batter                              BB McCullum
bowler                                  P Kumar
non_striker                          SC Ganguly
batsman_runs                                  0
extra_runs                                    0
total_runs                                    0
extras_type                              normal
is_wicket                                     0
player_dismissed                      No_wicket
dismissal_kind                        No_wicket
fielder                               No_wicket
Name: 1, dtype: object

In [74]:
total = df[((df['team1']=='Royal Challengers Bengaluru') & (df['team2']=='Chennai Super Kings')) | 
    ((df['team2']=='Royal Challengers Bengaluru') & (df['team1']=='Chennai Super Kings'))]['date'].nunique()
total

32

In [75]:
rcb = df[(((df['team1']=='Royal Challengers Bengaluru') & (df['team2']=='Chennai Super Kings')) | 
    ((df['team2']=='Royal Challengers Bengaluru') & (df['team1']=='Chennai Super Kings'))) &
    (df['winner']=='Royal Challengers Bengaluru')]['date'].nunique()
rcb

11

In [76]:
csk = df[(((df['team1']=='Royal Challengers Bengaluru') & (df['team2']=='Chennai Super Kings')) | 
    ((df['team2']=='Royal Challengers Bengaluru') & (df['team1']=='Chennai Super Kings'))) &
    (df['winner']=='Chennai Super Kings')]['date'].nunique()
csk

21

In [77]:
print('winning rate of rcb against csk is(upto 2024):-',rcb*100/total)

winning rate of rcb against csk is(upto 2024):- 34.375

In [78]:
print('winning rate of csk against rcb is(upto 2024):-',csk*100/total)

winning rate of csk against rcb is(upto 2024):- 65.625

In [79]:
df['season'].isin(['2008','2025']).unique()

array([ True, False])

In [80]:
df['target_runs'].between(43,288)

0         True
1         True
2         True
3         True
4         True
          ...
260915    True
260916    True
260917    True
260918    True
260919    True
Name: target_runs, Length: 260920, dtype: bool

In [81]:
df.query("(team1=='Mumbai Indians' and team2=='Chennai Super Kings')" or
         "(team2=='Mumbai Indians' and team1=='Chennai Super Kings')")

,index,match_id,season,city,date,match_type,player_of_match,venue,team1,team2,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
8248,8248,336018,2008,Mumbai,2008-05-14,League,ST Jayasuriya,Wankhede Stadium,Mumbai Indians,Chennai Super Kings,...,SM Pollock,SP Fleming,0,0,0,normal,0,No_wicket,No_wicket,No_wicket
8249,8249,336018,2008,Mumbai,2008-05-14,League,ST Jayasuriya,Wankhede Stadium,Mumbai Indians,Chennai Super Kings,...,SM Pollock,SP Fleming,1,0,1,normal,0,No_wicket,No_wicket,No_wicket
8250,8250,336018,2008,Mumbai,2008-05-14,League,ST Jayasuriya,Wankhede Stadium,Mumbai Indians,Chennai Super Kings,...,SM Pollock,S Vidyut,0,0,0,normal,0,No_wicket,No_wicket,No_wicket
8251,8251,336018,2008,Mumbai,2008-05-14,League,ST Jayasuriya,Wankhede Stadium,Mumbai Indians,Chennai Super Kings,...,SM Pollock,S Vidyut,0,0,0,normal,0,No_wicket,No_wicket,No_wicket
8252,8252,336018,2008,Mumbai,2008-05-14,League,ST Jayasuriya,Wankhede Stadium,Mumbai Indians,Chennai Super Kings,...,SM Pollock,S Vidyut,0,0,0,normal,0,No_wicket,No_wicket,No_wicket
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237790,237790,1359523,2023,Chennai,2023-05-06,League,M Pathirana,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Chennai Super Kings,...,Akash Madhwal,MS Dhoni,1,0,1,normal,0,No_wicket,No_wicket,No_wicket
237791,237791,1359523,2023,Chennai,2023-05-06,League,M Pathirana,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Chennai Super Kings,...,Arshad Khan,MS Dhoni,0,0,0,normal,0,No_wicket,No_wicket,No_wicket
237792,237792,1359523,2023,Chennai,2023-05-06,League,M Pathirana,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Chennai Super Kings,...,Arshad Khan,MS Dhoni,6,0,6,normal,0,No_wicket,No_wicket,No_wicket
237793,237793,1359523,2023,Chennai,2023-05-06,League,M Pathirana,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Chennai Super Kings,...,Arshad Khan,MS Dhoni,1,0,1,normal,0,No_wicket,No_wicket,No_wicket
237794,237794,1359523,2023,Chennai,2023-05-06,League,M Pathirana,"MA Chidambaram Stadium, Chepauk, Chennai",Mumbai Indians,Chennai Super Kings,...,Arshad Khan,S Dube,1,0,1,normal,0,No_wicket,No_wicket,No_wicket

In [82]:
df[df['team1'].isna()]

Empty DataFrame
Columns: [index, match_id, season, city, date, match_type, player_of_match, venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, target_runs, target_overs, super_over, method, umpire1, umpire2, inning, batting_team, bowling_team, over, ball, batter, bowler, non_striker, batsman_runs, extra_runs, total_runs, extras_type, is_wicket, player_dismissed, dismissal_kind, fielder]
Index: []

[0 rows x 37 columns]

In [83]:
df[~df['team1'].isna()]

,index,match_id,season,city,date,match_type,player_of_match,venue,team1,team2,...,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,0,335982,2008,Bengaluru,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,...,P Kumar,BB McCullum,0,1,1,legbyes,0,No_wicket,No_wicket,No_wicket
1,1,335982,2008,Bengaluru,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,...,P Kumar,SC Ganguly,0,0,0,normal,0,No_wicket,No_wicket,No_wicket
2,2,335982,2008,Bengaluru,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,...,P Kumar,SC Ganguly,0,1,1,wides,0,No_wicket,No_wicket,No_wicket
3,3,335982,2008,Bengaluru,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,...,P Kumar,SC Ganguly,0,0,0,normal,0,No_wicket,No_wicket,No_wicket
4,4,335982,2008,Bengaluru,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,...,P Kumar,SC Ganguly,0,0,0,normal,0,No_wicket,No_wicket,No_wicket
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,260915,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,...,AK Markram,VR Iyer,1,0,1,normal,0,No_wicket,No_wicket,No_wicket
260916,260916,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,...,AK Markram,SS Iyer,1,0,1,normal,0,No_wicket,No_wicket,No_wicket
260917,260917,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,...,Shahbaz Ahmed,SS Iyer,1,0,1,normal,0,No_wicket,No_wicket,No_wicket
260918,260918,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,...,Shahbaz Ahmed,VR Iyer,1,0,1,normal,0,No_wicket,No_wicket,No_wicket
260919,260919,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,...,Shahbaz Ahmed,SS Iyer,1,0,1,normal,0,No_wicket,No_wicket,No_wicket

In [84]:
df.set_index('season',inplace=True)

In [85]:
df.reset_index(inplace=True)

In [86]:
df.set_index('index',inplace=True)

In [87]:
df.set_index(['season','city'],inplace=True)

In [88]:
df.loc['2016','Bengaluru']

C:\Users\chahat\AppData\Local\Temp\ipykernel_14500\1651803940.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df.loc['2016','Bengaluru']

                  match_id        date match_type player_of_match  \
season city
2016   Bengaluru    980907  2016-04-12     League  AB de Villiers
       Bengaluru    980907  2016-04-12     League  AB de Villiers
       Bengaluru    980907  2016-04-12     League  AB de Villiers
       Bengaluru    980907  2016-04-12     League  AB de Villiers
       Bengaluru    980907  2016-04-12     League  AB de Villiers
...                    ...         ...        ...             ...
       Bengaluru    981019  2016-05-29      Final     BCJ Cutting
       Bengaluru    981019  2016-05-29      Final     BCJ Cutting
       Bengaluru    981019  2016-05-29      Final     BCJ Cutting
       Bengaluru    981019  2016-05-29      Final     BCJ Cutting
       Bengaluru    981019  2016-05-29      Final     BCJ Cutting

                                  venue                        team1  \
season city
2016   Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
...                                 ...                          ...
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru
       Bengaluru  M Chinnaswamy Stadium  Royal Challengers Bengaluru

                                team2          toss_winner toss_decision  \
season city
2016   Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad         field
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad         field
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad         field
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad         field
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad         field
...                               ...                  ...           ...
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad           bat
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad           bat
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad           bat
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad           bat
       Bengaluru  Sunrisers Hyderabad  Sunrisers Hyderabad           bat

                                       winner  ...   bowler    non_striker  \
season city                                    ...
2016   Bengaluru  Royal Challengers Bengaluru  ...  A Nehra        V Kohli
       Bengaluru  Royal Challengers Bengaluru  ...  A Nehra        V Kohli
       Bengaluru  Royal Challengers Bengaluru  ...  A Nehra       CH Gayle
       Bengaluru  Royal Challengers Bengaluru  ...  A Nehra       CH Gayle
       Bengaluru  Royal Challengers Bengaluru  ...  A Nehra       CH Gayle
...                                       ...  ...      ...            ...
       Bengaluru          Sunrisers Hyderabad  ...  B Kumar      CJ Jordan
       Bengaluru          Sunrisers Hyderabad  ...  B Kumar      CJ Jordan
       Bengaluru          Sunrisers Hyderabad  ...  B Kumar    Sachin Baby
       Bengaluru          Sunrisers Hyderabad  ...  B Kumar  Iqbal Abdulla
       Bengaluru          Sunrisers Hyderabad  ...  B Kumar    Sachin Baby

                  batsman_runs  extra_runs total_runs extras_type is_wicket  \
season city
2016   Bengaluru             0           0          0      normal         0
       Bengaluru             1           0          1      normal         0
       Bengaluru             0           0          0      normal         0
       Bengaluru             0           0          0      normal         0
       Bengaluru             0           0          0      normal         0
...                        ...         ...        ...         ...       ...
       Bengaluru             2           0          2      normal         0
       Bengaluru             0           0          0      normal         1
       Bengaluru             0           1          1     legbyes         0
       Bengaluru             1           0          1      normal         0
       Bengaluru             4           0          4      normal         0

                 player_dismissed  dismissal_kind    fielder
season city
2016   Bengaluru        No_wicket       No_wicket  No_wicket
       Bengaluru        No_wicket       No_wicket  No_wicket
       Bengaluru        No_wicket       No_wicket  No_wicket
       Bengaluru        No_wicket       No_wicket  No_wicket
       Bengaluru        No_wicket       No_wicket  No_wicket
...                           ...             ...        ...
       Bengaluru        No_wicket       No_wicket  No_wicket
       Bengaluru        CJ Jordan         run out    NV Ojha
       Bengaluru        No_wicket       No_wicket  No_wicket
       Bengaluru        No_wicket       No_wicket  No_wicket
       Bengaluru        No_wicket       No_wicket  No_wicket

[2147 rows x 34 columns]

In [91]:
df.reset_index(inplace=True)

In [92]:
df.set_index('index',inplace=True)

In [93]:
df.duplicated('match_id').unique()

array([False,  True])

In [94]:
df['date'] = pd.to_datetime(df['date'])

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 260920 entries, 0 to 260919
Data columns (total 36 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   season            260920 non-null  object
 1   city              260920 non-null  object
 2   match_id          260920 non-null  int64
 3   date              260920 non-null  datetime64[ns]
 4   match_type        260920 non-null  object
 5   player_of_match   260920 non-null  object
 6   venue             260920 non-null  object
 7   team1             260920 non-null  object
 8   team2             260920 non-null  object
 9   toss_winner       260920 non-null  object
 10  toss_decision     260920 non-null  object
 11  winner            260920 non-null  object
 12  result            260920 non-null  object
 13  result_margin     260920 non-null  float64
 14  target_runs       260920 non-null  float64
 15  target_overs      260920 non-null  float64
 16  super_over        260920 non-null  object
 17  method            260920 non-null  object
 18  umpire1           260920 non-null  object
 19  umpire2           260920 non-null  object
 20  inning            260920 non-null  int64
 21  batting_team      260920 non-null  object
 22  bowling_team      260920 non-null  object
 23  over              260920 non-null  int64
 24  ball              260920 non-null  int64
 25  batter            260920 non-null  object
 26  bowler            260920 non-null  object
 27  non_striker       260920 non-null  object
 28  batsman_runs      260920 non-null  int64
 29  extra_runs        260920 non-null  int64
 30  total_runs        260920 non-null  int64
 31  extras_type       260920 non-null  object
 32  is_wicket         260920 non-null  int64
 33  player_dismissed  260920 non-null  object
 34  dismissal_kind    260920 non-null  object
 35  fielder           260920 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(8), object(24)
memory usage: 73.7+ MB

In [96]:
df.columns.str.strip()

Index(['season', 'city', 'match_id', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2', 'inning', 'batting_team',
       'bowling_team', 'over', 'ball', 'batter', 'bowler', 'non_striker',
       'batsman_runs', 'extra_runs', 'total_runs', 'extras_type', 'is_wicket',
       'player_dismissed', 'dismissal_kind', 'fielder'],
      dtype='object')

In [97]:
df['toss_decision'].unique()

array(['field', 'bat'], dtype=object)

In [98]:
df1 = df.copy()

In [99]:
df = df.drop(['player_of_match','result','result_margin','target_runs','target_overs','super_over',
         'method','umpire1','umpire2','inning','batting_team','bowling_team','over','ball','batter','bowler','non_striker',
         'batsman_runs','extra_runs','total_runs','extras_type','is_wicket','player_dismissed','dismissal_kind','fielder'],axis=1)

In [100]:
df.isnull().sum()

season           0
city             0
match_id         0
date             0
match_type       0
venue            0
team1            0
team2            0
toss_winner      0
toss_decision    0
winner           0
dtype: int64

In [101]:
df['year'] = df['date'].dt.year

In [102]:
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

In [103]:
df = df.drop('date',axis=1)

In [104]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['winner'] = le.fit_transform(df['winner'])

In [105]:
df

,season,city,match_id,match_type,venue,team1,team2,toss_winner,toss_decision,winner,year,month,day
index,,,,,,,,,,,,,
0,2008,Bengaluru,335982,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,6,2008,4,18
1,2008,Bengaluru,335982,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,6,2008,4,18
2,2008,Bengaluru,335982,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,6,2008,4,18
3,2008,Bengaluru,335982,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,6,2008,4,18
4,2008,Bengaluru,335982,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,6,2008,4,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,2024,Chennai,1426312,Final,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,6,2024,5,26
260916,2024,Chennai,1426312,Final,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,6,2024,5,26
260917,2024,Chennai,1426312,Final,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,6,2024,5,26
260918,2024,Chennai,1426312,Final,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,6,2024,5,26
260919,2024,Chennai,1426312,Final,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,6,2024,5,26

In [106]:
cols = [
    'season',
    'city',
    'match_type',
    'venue',
    'team1',
    'team2',
    'toss_winner',
    'toss_decision'	
]
df = pd.get_dummies(df,columns=cols).astype('int')

In [107]:
df.columns

Index(['match_id', 'winner', 'year', 'month', 'day', 'season_2008',
       'season_2009', 'season_2010', 'season_2011', 'season_2012',
       ...
       'toss_winner_Lucknow Super Giants', 'toss_winner_Mumbai Indians',
       'toss_winner_Pune Warriors', 'toss_winner_Punjab Kings',
       'toss_winner_Rajasthan Royals', 'toss_winner_Rising Pune Supergiant',
       'toss_winner_Royal Challengers Bengaluru',
       'toss_winner_Sunrisers Hyderabad', 'toss_decision_bat',
       'toss_decision_field'],
      dtype='object', length=170)

In [108]:
df.shape

(260920, 170)

In [109]:
print(df.duplicated().sum())

259825

In [110]:
df = df.drop_duplicates()

In [111]:
df.shape

(1095, 170)

In [112]:
df.columns

Index(['match_id', 'winner', 'year', 'month', 'day', 'season_2008',
       'season_2009', 'season_2010', 'season_2011', 'season_2012',
       ...
       'toss_winner_Lucknow Super Giants', 'toss_winner_Mumbai Indians',
       'toss_winner_Pune Warriors', 'toss_winner_Punjab Kings',
       'toss_winner_Rajasthan Royals', 'toss_winner_Rising Pune Supergiant',
       'toss_winner_Royal Challengers Bengaluru',
       'toss_winner_Sunrisers Hyderabad', 'toss_decision_bat',
       'toss_decision_field'],
      dtype='object', length=170)

In [113]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

x = df.drop('winner',axis=1)
y = df['winner']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = RandomForestClassifier(n_estimators=500)
model.fit(x_train,y_train)
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

accuracy_test = accuracy_score(y_test,y_pred_test)
accuracy_train = accuracy_score(y_train,y_pred_train)
print('training accuracy:-',accuracy_train)
print('testing accuarcy:-',accuracy_test)

training accuracy:- 1.0
testing accuarcy:- 0.5205479452054794

In [114]:
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

x = df.drop('winner',axis=1)
y = df['winner']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = XGBClassifier(n_estimators=1000)
model.fit(x_train,y_train)
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

accuracy_test = accuracy_score(y_test,y_pred_test)
accuracy_train = accuracy_score(y_train,y_pred_train)
print('training accuracy:-',accuracy_train)
print('testing accuarcy:-',accuracy_test)

training accuracy:- 1.0
testing accuarcy:- 0.5296803652968036

In [115]:
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score

x = df.drop('winner',axis=1)
y = df['winner']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model = CatBoostClassifier(n_estimators=500)
model.fit(x_train,y_train)
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

accuracy_test = accuracy_score(y_test,y_pred_test)
accuracy_train = accuracy_score(y_train,y_pred_train)
print('training accuracy:-',accuracy_train)
print('testing accuarcy:-',accuracy_test)

Learning rate set to 0.141176
0:	learn: 2.6004085	total: 162ms	remaining: 1m 20s
1:	learn: 2.4961185	total: 179ms	remaining: 44.6s
2:	learn: 2.4039796	total: 196ms	remaining: 32.5s
3:	learn: 2.2856463	total: 211ms	remaining: 26.2s
4:	learn: 2.1608988	total: 228ms	remaining: 22.5s
5:	learn: 2.1022356	total: 244ms	remaining: 20.1s
6:	learn: 2.0226673	total: 261ms	remaining: 18.4s
7:	learn: 1.9787985	total: 277ms	remaining: 17s
8:	learn: 1.9371365	total: 293ms	remaining: 16s
9:	learn: 1.9055175	total: 309ms	remaining: 15.1s
10:	learn: 1.8676528	total: 324ms	remaining: 14.4s
11:	learn: 1.7990975	total: 340ms	remaining: 13.8s
12:	learn: 1.7632870	total: 357ms	remaining: 13.4s
13:	learn: 1.7239674	total: 373ms	remaining: 13s
14:	learn: 1.6947792	total: 390ms	remaining: 12.6s
15:	learn: 1.6632384	total: 406ms	remaining: 12.3s
16:	learn: 1.6379143	total: 423ms	remaining: 12s
17:	learn: 1.6100408	total: 439ms	remaining: 11.8s
18:	learn: 1.5825316	total: 456ms	remaining: 11.5s
19:	learn: 1.5583297	total: 472ms	remaining: 11.3s
20:	learn: 1.5398307	total: 488ms	remaining: 11.1s
21:	learn: 1.5219874	total: 504ms	remaining: 11s
22:	learn: 1.5048206	total: 520ms	remaining: 10.8s
23:	learn: 1.4785047	total: 537ms	remaining: 10.7s
24:	learn: 1.4511865	total: 554ms	remaining: 10.5s
25:	learn: 1.4312733	total: 570ms	remaining: 10.4s
26:	learn: 1.4195903	total: 588ms	remaining: 10.3s
27:	learn: 1.3983307	total: 604ms	remaining: 10.2s
28:	learn: 1.3814385	total: 621ms	remaining: 10.1s
29:	learn: 1.3648230	total: 638ms	remaining: 9.99s
30:	learn: 1.3496942	total: 654ms	remaining: 9.89s
31:	learn: 1.3388044	total: 670ms	remaining: 9.8s
32:	learn: 1.3222878	total: 687ms	remaining: 9.72s
33:	learn: 1.3087554	total: 703ms	remaining: 9.64s
34:	learn: 1.2925881	total: 719ms	remaining: 9.56s
35:	learn: 1.2794188	total: 735ms	remaining: 9.47s
36:	learn: 1.2673613	total: 752ms	remaining: 9.4s
37:	learn: 1.2553893	total: 768ms	remaining: 9.34s
38:	learn: 1.2466246	total: 785ms	remaining: 9.28s
39:	learn: 1.2350411	total: 802ms	remaining: 9.23s
40:	learn: 1.2235563	total: 817ms	remaining: 9.15s
41:	learn: 1.2101183	total: 835ms	remaining: 9.11s
42:	learn: 1.1980434	total: 852ms	remaining: 9.05s
43:	learn: 1.1890914	total: 869ms	remaining: 9.01s
44:	learn: 1.1790184	total: 886ms	remaining: 8.96s
45:	learn: 1.1666982	total: 903ms	remaining: 8.91s
46:	learn: 1.1527035	total: 919ms	remaining: 8.86s
47:	learn: 1.1430114	total: 934ms	remaining: 8.79s
48:	learn: 1.1276477	total: 949ms	remaining: 8.73s
49:	learn: 1.1193336	total: 965ms	remaining: 8.69s
50:	learn: 1.1070205	total: 982ms	remaining: 8.64s
51:	learn: 1.0918541	total: 998ms	remaining: 8.6s
52:	learn: 1.0793486	total: 1.01s	remaining: 8.55s
53:	learn: 1.0708063	total: 1.03s	remaining: 8.51s
54:	learn: 1.0633167	total: 1.05s	remaining: 8.47s
55:	learn: 1.0502912	total: 1.06s	remaining: 8.43s
56:	learn: 1.0403253	total: 1.08s	remaining: 8.39s
57:	learn: 1.0289567	total: 1.09s	remaining: 8.35s
58:	learn: 1.0213502	total: 1.11s	remaining: 8.31s
59:	learn: 1.0123626	total: 1.13s	remaining: 8.27s
60:	learn: 1.0009542	total: 1.14s	remaining: 8.24s
61:	learn: 0.9944018	total: 1.16s	remaining: 8.2s
62:	learn: 0.9880410	total: 1.18s	remaining: 8.17s
63:	learn: 0.9802412	total: 1.19s	remaining: 8.13s
64:	learn: 0.9677965	total: 1.21s	remaining: 8.1s
65:	learn: 0.9591211	total: 1.23s	remaining: 8.06s
66:	learn: 0.9507139	total: 1.24s	remaining: 8.03s
67:	learn: 0.9392113	total: 1.26s	remaining: 8.03s
68:	learn: 0.9297121	total: 1.28s	remaining: 8.02s
69:	learn: 0.9235735	total: 1.3s	remaining: 8s
70:	learn: 0.9154797	total: 1.32s	remaining: 7.97s
71:	learn: 0.9069378	total: 1.34s	remaining: 7.94s
72:	learn: 0.8995261	total: 1.35s	remaining: 7.91s
73:	learn: 0.8936648	total: 1.37s	remaining: 7.88s
74:	learn: 0.8871347	total: 1.39s	remaining: 7.85s
75:	learn: 0.8787947	total: 1.4s	remaining: 7.81s
76:	learn: 0.8721088	total: 1.42s	remaining: 7.78s
77:	learn: 0.8655211	total: 1.48s	remaining: 7.99s
78:	learn: 0.8573552	total: 1.51s	remaining: 8.06s
79:	learn: 0.8520603	total: 1.53s	remaining: 8.04s
80:	learn: 0.8463399	total: 1.55s	remaining: 8.03s
81:	learn: 0.8394969	total: 1.57s	remaining: 8.01s
82:	learn: 0.8332072	total: 1.59s	remaining: 7.98s
83:	learn: 0.8292821	total: 1.6s	remaining: 7.95s
84:	learn: 0.8246637	total: 1.62s	remaining: 7.91s
85:	learn: 0.8185253	total: 1.64s	remaining: 7.88s
86:	learn: 0.8123532	total: 1.65s	remaining: 7.84s
87:	learn: 0.8060627	total: 1.67s	remaining: 7.81s
88:	learn: 0.8006579	total: 1.68s	remaining: 7.78s
89:	learn: 0.7953503	total: 1.7s	remaining: 7.75s
90:	learn: 0.7885379	total: 1.72s	remaining: 7.72s
91:	learn: 0.7842086	total: 1.73s	remaining: 7.69s
92:	learn: 0.7796738	total: 1.75s	remaining: 7.66s
93:	learn: 0.7745716	total: 1.77s	remaining: 7.63s
94:	learn: 0.7710042	total: 1.78s	remaining: 7.6s
95:	learn: 0.7658493	total: 1.8s	remaining: 7.58s
96:	learn: 0.7621020	total: 1.82s	remaining: 7.55s
97:	learn: 0.7583765	total: 1.83s	remaining: 7.52s
98:	learn: 0.7541225	total: 1.85s	remaining: 7.49s
99:	learn: 0.7494224	total: 1.87s	remaining: 7.47s
100:	learn: 0.7441462	total: 1.88s	remaining: 7.44s
101:	learn: 0.7406530	total: 1.9s	remaining: 7.41s
102:	learn: 0.7362064	total: 1.92s	remaining: 7.38s
103:	learn: 0.7324279	total: 1.93s	remaining: 7.36s
104:	learn: 0.7271282	total: 1.95s	remaining: 7.33s
105:	learn: 0.7222328	total: 1.97s	remaining: 7.31s
106:	learn: 0.7167801	total: 1.98s	remaining: 7.28s
107:	learn: 0.7126437	total: 2s	remaining: 7.25s
108:	learn: 0.7089017	total: 2.01s	remaining: 7.23s
109:	learn: 0.7059370	total: 2.03s	remaining: 7.2s
110:	learn: 0.7028736	total: 2.05s	remaining: 7.18s
111:	learn: 0.6992473	total: 2.06s	remaining: 7.15s
112:	learn: 0.6963690	total: 2.08s	remaining: 7.12s
113:	learn: 0.6935087	total: 2.1s	remaining: 7.1s
114:	learn: 0.6884011	total: 2.11s	remaining: 7.08s
115:	learn: 0.6842068	total: 2.13s	remaining: 7.05s
116:	learn: 0.6792341	total: 2.15s	remaining: 7.03s
117:	learn: 0.6753577	total: 2.17s	remaining: 7.01s
118:	learn: 0.6718278	total: 2.18s	remaining: 6.99s
119:	learn: 0.6693548	total: 2.2s	remaining: 6.96s
120:	learn: 0.6655716	total: 2.21s	remaining: 6.94s
121:	learn: 0.6619146	total: 2.23s	remaining: 6.91s
122:	learn: 0.6574071	total: 2.25s	remaining: 6.89s
123:	learn: 0.6542792	total: 2.26s	remaining: 6.87s
124:	learn: 0.6501452	total: 2.28s	remaining: 6.84s
125:	learn: 0.6461332	total: 2.3s	remaining: 6.82s
126:	learn: 0.6427621	total: 2.31s	remaining: 6.79s
127:	learn: 0.6385576	total: 2.33s	remaining: 6.77s
128:	learn: 0.6352706	total: 2.35s	remaining: 6.75s
129:	learn: 0.6308999	total: 2.36s	remaining: 6.73s
130:	learn: 0.6276223	total: 2.38s	remaining: 6.7s
131:	learn: 0.6251369	total: 2.4s	remaining: 6.68s
132:	learn: 0.6215263	total: 2.41s	remaining: 6.65s
133:	learn: 0.6202483	total: 2.43s	remaining: 6.63s
134:	learn: 0.6172705	total: 2.44s	remaining: 6.61s
135:	learn: 0.6137105	total: 2.46s	remaining: 6.58s
136:	learn: 0.6103351	total: 2.48s	remaining: 6.56s
137:	learn: 0.6071212	total: 2.49s	remaining: 6.54s
138:	learn: 0.6036991	total: 2.51s	remaining: 6.52s
139:	learn: 0.5992776	total: 2.53s	remaining: 6.5s
140:	learn: 0.5962178	total: 2.54s	remaining: 6.48s
141:	learn: 0.5929317	total: 2.56s	remaining: 6.46s
142:	learn: 0.5902026	total: 2.58s	remaining: 6.44s
143:	learn: 0.5877569	total: 2.6s	remaining: 6.42s
144:	learn: 0.5852004	total: 2.61s	remaining: 6.4s
145:	learn: 0.5811864	total: 2.63s	remaining: 6.38s
146:	learn: 0.5796279	total: 2.65s	remaining: 6.36s
147:	learn: 0.5768629	total: 2.66s	remaining: 6.34s
148:	learn: 0.5745610	total: 2.68s	remaining: 6.32s
149:	learn: 0.5715011	total: 2.7s	remaining: 6.29s
150:	learn: 0.5692414	total: 2.71s	remaining: 6.28s
151:	learn: 0.5667762	total: 2.73s	remaining: 6.25s
152:	learn: 0.5629354	total: 2.75s	remaining: 6.23s
153:	learn: 0.5591695	total: 2.76s	remaining: 6.21s
154:	learn: 0.5570655	total: 2.78s	remaining: 6.19s
155:	learn: 0.5545534	total: 2.8s	remaining: 6.17s
156:	learn: 0.5515881	total: 2.81s	remaining: 6.15s
157:	learn: 0.5495407	total: 2.83s	remaining: 6.13s
158:	learn: 0.5466772	total: 2.85s	remaining: 6.11s
159:	learn: 0.5434322	total: 2.86s	remaining: 6.08s
160:	learn: 0.5403047	total: 2.88s	remaining: 6.06s
161:	learn: 0.5385109	total: 2.9s	remaining: 6.04s
162:	learn: 0.5367260	total: 2.91s	remaining: 6.02s
163:	learn: 0.5345884	total: 2.93s	remaining: 6s
164:	learn: 0.5304446	total: 2.94s	remaining: 5.98s
165:	learn: 0.5280956	total: 2.96s	remaining: 5.96s
166:	learn: 0.5262620	total: 2.98s	remaining: 5.94s
167:	learn: 0.5245210	total: 3s	remaining: 5.92s
168:	learn: 0.5215748	total: 3.01s	remaining: 5.9s
169:	learn: 0.5193813	total: 3.02s	remaining: 5.87s
170:	learn: 0.5175300	total: 3.04s	remaining: 5.85s
171:	learn: 0.5157789	total: 3.06s	remaining: 5.83s
172:	learn: 0.5131887	total: 3.07s	remaining: 5.8s
173:	learn: 0.5107298	total: 3.09s	remaining: 5.78s
174:	learn: 0.5078438	total: 3.1s	remaining: 5.76s
175:	learn: 0.5052433	total: 3.12s	remaining: 5.74s
176:	learn: 0.5030105	total: 3.13s	remaining: 5.72s
177:	learn: 0.5011202	total: 3.15s	remaining: 5.7s
178:	learn: 0.4988150	total: 3.17s	remaining: 5.68s
179:	learn: 0.4967019	total: 3.18s	remaining: 5.66s
180:	learn: 0.4952226	total: 3.2s	remaining: 5.64s
181:	learn: 0.4927891	total: 3.22s	remaining: 5.62s
182:	learn: 0.4914025	total: 3.23s	remaining: 5.6s
183:	learn: 0.4889244	total: 3.25s	remaining: 5.58s
184:	learn: 0.4866317	total: 3.27s	remaining: 5.56s
185:	learn: 0.4841963	total: 3.28s	remaining: 5.54s
186:	learn: 0.4823793	total: 3.3s	remaining: 5.52s
187:	learn: 0.4804442	total: 3.31s	remaining: 5.5s
188:	learn: 0.4786075	total: 3.33s	remaining: 5.48s
189:	learn: 0.4766320	total: 3.35s	remaining: 5.46s
190:	learn: 0.4754302	total: 3.36s	remaining: 5.44s
191:	learn: 0.4736970	total: 3.38s	remaining: 5.42s
192:	learn: 0.4719567	total: 3.4s	remaining: 5.4s
193:	learn: 0.4699770	total: 3.41s	remaining: 5.38s
194:	learn: 0.4683201	total: 3.43s	remaining: 5.37s
195:	learn: 0.4668911	total: 3.45s	remaining: 5.34s
196:	learn: 0.4650346	total: 3.46s	remaining: 5.33s
197:	learn: 0.4636979	total: 3.48s	remaining: 5.3s
198:	learn: 0.4607999	total: 3.5s	remaining: 5.29s
199:	learn: 0.4593664	total: 3.51s	remaining: 5.27s
200:	learn: 0.4579943	total: 3.53s	remaining: 5.25s
201:	learn: 0.4556188	total: 3.54s	remaining: 5.23s
202:	learn: 0.4531088	total: 3.56s	remaining: 5.21s
203:	learn: 0.4511534	total: 3.58s	remaining: 5.19s
204:	learn: 0.4495096	total: 3.59s	remaining: 5.17s
205:	learn: 0.4478336	total: 3.61s	remaining: 5.15s
206:	learn: 0.4452683	total: 3.62s	remaining: 5.13s
207:	learn: 0.4430366	total: 3.64s	remaining: 5.11s
208:	learn: 0.4419623	total: 3.66s	remaining: 5.09s
209:	learn: 0.4395658	total: 3.67s	remaining: 5.07s
210:	learn: 0.4373345	total: 3.69s	remaining: 5.05s
211:	learn: 0.4346145	total: 3.71s	remaining: 5.03s
212:	learn: 0.4310787	total: 3.72s	remaining: 5.01s
213:	learn: 0.4287598	total: 3.74s	remaining: 5s
214:	learn: 0.4275347	total: 3.75s	remaining: 4.97s
215:	learn: 0.4262147	total: 3.77s	remaining: 4.95s
216:	learn: 0.4250500	total: 3.78s	remaining: 4.93s
217:	learn: 0.4233015	total: 3.8s	remaining: 4.91s
218:	learn: 0.4221524	total: 3.81s	remaining: 4.89s
219:	learn: 0.4204008	total: 3.83s	remaining: 4.87s
220:	learn: 0.4189904	total: 3.85s	remaining: 4.85s
221:	learn: 0.4172919	total: 3.86s	remaining: 4.83s
222:	learn: 0.4152546	total: 3.88s	remaining: 4.81s
223:	learn: 0.4131667	total: 3.89s	remaining: 4.79s
224:	learn: 0.4112135	total: 3.91s	remaining: 4.78s
225:	learn: 0.4094696	total: 3.92s	remaining: 4.76s
226:	learn: 0.4084026	total: 3.94s	remaining: 4.74s
227:	learn: 0.4072815	total: 3.95s	remaining: 4.72s
228:	learn: 0.4063235	total: 3.97s	remaining: 4.7s
229:	learn: 0.4051503	total: 3.98s	remaining: 4.67s
230:	learn: 0.4033351	total: 4s	remaining: 4.66s
231:	learn: 0.4021300	total: 4.01s	remaining: 4.64s
232:	learn: 0.4008896	total: 4.03s	remaining: 4.62s
233:	learn: 0.3999570	total: 4.05s	remaining: 4.6s
234:	learn: 0.3982280	total: 4.06s	remaining: 4.58s
235:	learn: 0.3970336	total: 4.08s	remaining: 4.56s
236:	learn: 0.3963332	total: 4.09s	remaining: 4.54s
237:	learn: 0.3941730	total: 4.11s	remaining: 4.52s
238:	learn: 0.3929240	total: 4.13s	remaining: 4.5s
239:	learn: 0.3914448	total: 4.14s	remaining: 4.49s
240:	learn: 0.3899884	total: 4.16s	remaining: 4.47s
241:	learn: 0.3883150	total: 4.17s	remaining: 4.45s
242:	learn: 0.3875719	total: 4.19s	remaining: 4.43s
243:	learn: 0.3861949	total: 4.2s	remaining: 4.41s
244:	learn: 0.3851306	total: 4.22s	remaining: 4.39s
245:	learn: 0.3837756	total: 4.23s	remaining: 4.37s
246:	learn: 0.3821554	total: 4.25s	remaining: 4.35s
247:	learn: 0.3809845	total: 4.26s	remaining: 4.33s
248:	learn: 0.3801327	total: 4.28s	remaining: 4.31s
249:	learn: 0.3783700	total: 4.29s	remaining: 4.29s
250:	learn: 0.3769714	total: 4.31s	remaining: 4.27s
251:	learn: 0.3760433	total: 4.32s	remaining: 4.25s
252:	learn: 0.3750831	total: 4.34s	remaining: 4.24s
253:	learn: 0.3737580	total: 4.35s	remaining: 4.22s
254:	learn: 0.3721852	total: 4.37s	remaining: 4.2s
255:	learn: 0.3706205	total: 4.38s	remaining: 4.18s
256:	learn: 0.3685136	total: 4.4s	remaining: 4.16s
257:	learn: 0.3667176	total: 4.41s	remaining: 4.14s
258:	learn: 0.3656753	total: 4.43s	remaining: 4.12s
259:	learn: 0.3642532	total: 4.44s	remaining: 4.1s
260:	learn: 0.3629718	total: 4.46s	remaining: 4.08s
261:	learn: 0.3612984	total: 4.48s	remaining: 4.07s
262:	learn: 0.3601236	total: 4.49s	remaining: 4.05s
263:	learn: 0.3588965	total: 4.51s	remaining: 4.03s
264:	learn: 0.3582756	total: 4.52s	remaining: 4.01s
265:	learn: 0.3571813	total: 4.54s	remaining: 3.99s
266:	learn: 0.3563460	total: 4.55s	remaining: 3.97s
267:	learn: 0.3551354	total: 4.57s	remaining: 3.95s
268:	learn: 0.3537312	total: 4.58s	remaining: 3.93s
269:	learn: 0.3522737	total: 4.6s	remaining: 3.92s
270:	learn: 0.3509346	total: 4.61s	remaining: 3.9s
271:	learn: 0.3498588	total: 4.63s	remaining: 3.88s
272:	learn: 0.3486228	total: 4.64s	remaining: 3.86s
273:	learn: 0.3474258	total: 4.66s	remaining: 3.84s
274:	learn: 0.3465411	total: 4.68s	remaining: 3.83s
275:	learn: 0.3452366	total: 4.69s	remaining: 3.81s
276:	learn: 0.3446748	total: 4.71s	remaining: 3.79s
277:	learn: 0.3436649	total: 4.73s	remaining: 3.77s
278:	learn: 0.3424492	total: 4.74s	remaining: 3.76s
279:	learn: 0.3416626	total: 4.76s	remaining: 3.74s
280:	learn: 0.3403176	total: 4.78s	remaining: 3.72s
281:	learn: 0.3390478	total: 4.79s	remaining: 3.71s
282:	learn: 0.3379791	total: 4.81s	remaining: 3.69s
283:	learn: 0.3372451	total: 4.83s	remaining: 3.67s
284:	learn: 0.3358721	total: 4.84s	remaining: 3.65s
285:	learn: 0.3347389	total: 4.86s	remaining: 3.64s
286:	learn: 0.3337300	total: 4.88s	remaining: 3.62s
287:	learn: 0.3324466	total: 4.89s	remaining: 3.6s
288:	learn: 0.3310000	total: 4.91s	remaining: 3.58s
289:	learn: 0.3300342	total: 4.92s	remaining: 3.57s
290:	learn: 0.3288825	total: 4.94s	remaining: 3.55s
291:	learn: 0.3272413	total: 4.96s	remaining: 3.53s
292:	learn: 0.3260700	total: 4.97s	remaining: 3.51s
293:	learn: 0.3250725	total: 4.99s	remaining: 3.5s
294:	learn: 0.3236709	total: 5.01s	remaining: 3.48s
295:	learn: 0.3225418	total: 5.02s	remaining: 3.46s
296:	learn: 0.3218370	total: 5.04s	remaining: 3.44s
297:	learn: 0.3204477	total: 5.05s	remaining: 3.43s
298:	learn: 0.3197994	total: 5.07s	remaining: 3.41s
299:	learn: 0.3183944	total: 5.09s	remaining: 3.39s
300:	learn: 0.3172310	total: 5.1s	remaining: 3.37s
301:	learn: 0.3164088	total: 5.12s	remaining: 3.36s
302:	learn: 0.3155078	total: 5.13s	remaining: 3.34s
303:	learn: 0.3145545	total: 5.15s	remaining: 3.32s
304:	learn: 0.3135419	total: 5.17s	remaining: 3.3s
305:	learn: 0.3127125	total: 5.18s	remaining: 3.28s
306:	learn: 0.3115712	total: 5.2s	remaining: 3.27s
307:	learn: 0.3108650	total: 5.21s	remaining: 3.25s
308:	learn: 0.3097034	total: 5.23s	remaining: 3.23s
309:	learn: 0.3086796	total: 5.24s	remaining: 3.21s
310:	learn: 0.3077715	total: 5.26s	remaining: 3.2s
311:	learn: 0.3066107	total: 5.28s	remaining: 3.18s
312:	learn: 0.3059791	total: 5.29s	remaining: 3.16s
313:	learn: 0.3051737	total: 5.31s	remaining: 3.14s
314:	learn: 0.3041888	total: 5.32s	remaining: 3.13s
315:	learn: 0.3031072	total: 5.34s	remaining: 3.11s
316:	learn: 0.3020860	total: 5.36s	remaining: 3.09s
317:	learn: 0.3015320	total: 5.37s	remaining: 3.07s
318:	learn: 0.3004616	total: 5.39s	remaining: 3.06s
319:	learn: 0.2995430	total: 5.4s	remaining: 3.04s
320:	learn: 0.2989815	total: 5.42s	remaining: 3.02s
321:	learn: 0.2980009	total: 5.43s	remaining: 3s
322:	learn: 0.2971403	total: 5.45s	remaining: 2.99s
323:	learn: 0.2961388	total: 5.46s	remaining: 2.97s
324:	learn: 0.2957052	total: 5.48s	remaining: 2.95s
325:	learn: 0.2948150	total: 5.5s	remaining: 2.93s
326:	learn: 0.2940006	total: 5.51s	remaining: 2.92s
327:	learn: 0.2929766	total: 5.53s	remaining: 2.9s
328:	learn: 0.2919323	total: 5.55s	remaining: 2.88s
329:	learn: 0.2913801	total: 5.56s	remaining: 2.87s
330:	learn: 0.2905609	total: 5.58s	remaining: 2.85s
331:	learn: 0.2891150	total: 5.59s	remaining: 2.83s
332:	learn: 0.2881283	total: 5.61s	remaining: 2.81s
333:	learn: 0.2877308	total: 5.63s	remaining: 2.8s
334:	learn: 0.2866372	total: 5.64s	remaining: 2.78s
335:	learn: 0.2858755	total: 5.66s	remaining: 2.76s
336:	learn: 0.2848775	total: 5.68s	remaining: 2.75s
337:	learn: 0.2842331	total: 5.69s	remaining: 2.73s
338:	learn: 0.2836766	total: 5.71s	remaining: 2.71s
339:	learn: 0.2826579	total: 5.73s	remaining: 2.69s
340:	learn: 0.2815477	total: 5.74s	remaining: 2.68s
341:	learn: 0.2806513	total: 5.76s	remaining: 2.66s
342:	learn: 0.2801432	total: 5.78s	remaining: 2.65s
343:	learn: 0.2790788	total: 5.79s	remaining: 2.63s
344:	learn: 0.2784376	total: 5.81s	remaining: 2.61s
345:	learn: 0.2772187	total: 5.83s	remaining: 2.59s
346:	learn: 0.2760115	total: 5.84s	remaining: 2.58s
347:	learn: 0.2752350	total: 5.86s	remaining: 2.56s
348:	learn: 0.2746424	total: 5.88s	remaining: 2.54s
349:	learn: 0.2736935	total: 5.89s	remaining: 2.52s
350:	learn: 0.2731320	total: 5.91s	remaining: 2.51s
351:	learn: 0.2725615	total: 5.92s	remaining: 2.49s
352:	learn: 0.2714804	total: 5.94s	remaining: 2.47s
353:	learn: 0.2706550	total: 5.96s	remaining: 2.46s
354:	learn: 0.2696595	total: 5.97s	remaining: 2.44s
355:	learn: 0.2686192	total: 5.99s	remaining: 2.42s
356:	learn: 0.2677349	total: 6s	remaining: 2.4s
357:	learn: 0.2670238	total: 6.02s	remaining: 2.39s
358:	learn: 0.2663550	total: 6.04s	remaining: 2.37s
359:	learn: 0.2653145	total: 6.05s	remaining: 2.35s
360:	learn: 0.2643373	total: 6.07s	remaining: 2.34s
361:	learn: 0.2637930	total: 6.08s	remaining: 2.32s
362:	learn: 0.2632805	total: 6.1s	remaining: 2.3s
363:	learn: 0.2621350	total: 6.11s	remaining: 2.28s
364:	learn: 0.2616781	total: 6.13s	remaining: 2.27s
365:	learn: 0.2610894	total: 6.14s	remaining: 2.25s
366:	learn: 0.2601960	total: 6.16s	remaining: 2.23s
367:	learn: 0.2597540	total: 6.17s	remaining: 2.21s
368:	learn: 0.2593329	total: 6.19s	remaining: 2.2s
369:	learn: 0.2583448	total: 6.2s	remaining: 2.18s
370:	learn: 0.2572827	total: 6.22s	remaining: 2.16s
371:	learn: 0.2565103	total: 6.24s	remaining: 2.15s
372:	learn: 0.2556791	total: 6.25s	remaining: 2.13s
373:	learn: 0.2549305	total: 6.27s	remaining: 2.11s
374:	learn: 0.2540762	total: 6.29s	remaining: 2.1s
375:	learn: 0.2531347	total: 6.3s	remaining: 2.08s
376:	learn: 0.2525198	total: 6.32s	remaining: 2.06s
377:	learn: 0.2516910	total: 6.34s	remaining: 2.04s
378:	learn: 0.2501806	total: 6.35s	remaining: 2.03s
379:	learn: 0.2491294	total: 6.37s	remaining: 2.01s
380:	learn: 0.2487184	total: 6.39s	remaining: 1.99s
381:	learn: 0.2479029	total: 6.4s	remaining: 1.98s
382:	learn: 0.2470909	total: 6.42s	remaining: 1.96s
383:	learn: 0.2462160	total: 6.43s	remaining: 1.94s
384:	learn: 0.2454437	total: 6.45s	remaining: 1.93s
385:	learn: 0.2447511	total: 6.47s	remaining: 1.91s
386:	learn: 0.2439174	total: 6.48s	remaining: 1.89s
387:	learn: 0.2434195	total: 6.5s	remaining: 1.88s